shellEmulator: true

trustPolicy: no-downgrade

packages: []
catalogs:
  build:
    '@iconify-json/carbon': ^1.2.19
    '@vitejs/plugin-vue': ^6.0.4
    jsdom: ^28.1.0
    unocss: ^66.6.2
    unplugin: ^3.0.0
    unplugin-auto-import: ^21.0.0
    unplugin-vue-components: ^31.0.0
    unplugin-vue-macros: ^2.14.5
    vite: ^7.3.1
  dev:
    '@antfu/eslint-config': ^7.6.1
    '@types/node': ^25.3.3
    '@unocss/eslint-plugin': ^66.6.3
    '@vue-macros/volar': ^3.1.2
    '@vue/test-utils': ^2.4.6
    eslint: ^10.0.2
    eslint-plugin-format: ^2.0.1
    lint-staged: ^16.3.1
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    typescript: ^5.9.3
    vitest: ^4.0.18
    vue-tsc: ^3.2.5
  frontend:
    '@vueuse/core': ^14.2.1
    vue: ^3.5.29
    vue-router: ^5.0.3
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
